function ue = sol_analytic_fun(x, arg_sqlam, arg_beta, arg_eps)
    coeff_denom = 2.0 * ( 1 + cos(arg_sqlam)*cosh(arg_sqlam) +...
        ( 1j * arg_beta * arg_sqlam * arg_eps) / (1 + 1j * arg_beta * arg_sqlam * arg_sqlam ) * ...
        ( sin(arg_sqlam)* cosh(arg_sqlam) +  cos(arg_sqlam)* sinh(arg_sqlam) )  );
    Ae = ( 1 +  cos(arg_sqlam)* cosh(arg_sqlam) -...
        sin(arg_sqlam)* sinh(arg_sqlam) +...
        ( 2 * 1j * arg_beta * arg_sqlam * arg_eps) /...
        (1 + 1j * arg_beta * arg_sqlam * arg_sqlam ) *...
        cos(arg_sqlam)* sinh(arg_sqlam) ) / coeff_denom;
    Be = (  sin(arg_sqlam)* cosh(arg_sqlam) +...
        cos(arg_sqlam)* sinh(arg_sqlam) +...
        ( 2 * 1j * arg_beta * arg_sqlam * arg_eps) /...
        (1 + 1j * arg_beta * arg_sqlam * arg_sqlam ) *...
        sin(arg_sqlam)* sinh(arg_sqlam) ) / coeff_denom;
    Ce = 1 - Ae;
    De = - Be;

    ue = Ae *  cos(arg_sqlam*x) + Be *  sin(arg_sqlam*x) +...
        Ce *  cosh(arg_sqlam*x) + De *  sinh(arg_sqlam*x);
end