(* ::Package:: *)

(* ::Input:: *)
(*DIMmp = {-1,1,0,0};*)
(*DIMlp = {3,1,-2,0};*)
(*DIMbp = {1,0,0,0};*)
(*DIMep = {0,0,1,1};*)
(*DIMcp = {-2,-1,4,2};*)
(*DIMsb = {0,0,-1,0};*)
(*DIMrl = {2,1,-3,-2};*)
(*DIMxb  =  {1,0,0,0};*)
(*DIMmat = {DIMmp, DIMlp, DIMbp, DIMep, DIMcp, DIMsb, DIMrl,DIMxb};*)
(*PImat = NullSpace[Transpose[DIMmat]];*)
(*{MatrixForm[DIMmat],MatrixForm[PImat]}*)
(*PImat.DIMmat*)


(* ::InheritFromParent:: *)
(*{\!\(\**)
(*TagBox[*)
(*RowBox[{"(", "", GridBox[{*)
(*{*)
(*RowBox[{"-", "1"}], "1", "0", "0"},*)
(*{"3", "1", *)
(*RowBox[{"-", "2"}], "0"},*)
(*{"1", "0", "0", "0"},*)
(*{"0", "0", "1", "1"},*)
(*{*)
(*RowBox[{"-", "2"}], *)
(*RowBox[{"-", "1"}], "4", "2"},*)
(*{"0", "0", *)
(*RowBox[{"-", "1"}], "0"},*)
(*{"2", "1", *)
(*RowBox[{"-", "3"}], *)
(*RowBox[{"-", "2"}]},*)
(*{"1", "0", "0", "0"}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}}], "", ")"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\),\!\(\**)
(*TagBox[*)
(*RowBox[{"(", "", GridBox[{*)
(*{"0", "0", *)
(*RowBox[{"-", "1"}], "0", "0", "0", "0", "1"},*)
(*{*)
(*RowBox[{"-", "1"}], *)
(*RowBox[{"-", "1"}], *)
(*RowBox[{"-", "2"}], "4", "0", "0", "2", "0"},*)
(*{"1", *)
(*RowBox[{"-", "1"}], "4", "0", "0", "2", "0", "0"},*)
(*{"0", "1", *)
(*RowBox[{"-", "1"}], *)
(*RowBox[{"-", "2"}], "1", "0", "0", "0"}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}}], "", ")"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\)}*)


a = RandomInteger[{0, 10}, {5, 2}]
m = NullSpace[a]
{MatrixForm[m], MatrixForm[a]}



